CREATE DATABASE `cop2009` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
use cop2009;

-- SANCIONES
CREATE TABLE IF NOT EXISTS `cop2009`.`sanciones` (
  `reporte_num` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `sancion` VARCHAR(20) NULL DEFAULT NULL,
  `falta` VARCHAR(50) NULL DEFAULT NULL,
  `literal` VARCHAR(50) NULL DEFAULT NULL,
  `No_boleta` VARCHAR(20) NULL DEFAULT NULL,
  `placa` VARCHAR(20) NULL DEFAULT NULL,
  `marca` VARCHAR(20) NULL DEFAULT '-',
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_transporte` VARCHAR(50) NULL DEFAULT NULL,
  `empresa` VARCHAR(50) NULL DEFAULT NULL,
  `seguro` VARCHAR(50) NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `licencia` VARCHAR(50) NULL DEFAULT NULL,
  `tipo_licencia` VARCHAR(1) NULL DEFAULT NULL,
  `cedula` VARCHAR(50) NULL DEFAULT NULL,
  `edad` SMALLINT(5) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `excusa` VARCHAR(200) NULL DEFAULT NULL,
  `impuso` VARCHAR(10) NULL DEFAULT NULL,
  `agente_impuso` VARCHAR(50) NULL DEFAULT NULL,
  `id` DOUBLE UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `FALTASSANCIONES` (`falta` ASC) VISIBLE,
  INDEX `TIPO_TRANSPORTESANCIONES` (`tipo_transporte` ASC) VISIBLE,
  INDEX `TIPO_VEHICULOSANCIONES` (`tipo` ASC) VISIBLE,
  INDEX `numreporte` (`reporte_num` ASC) VISIBLE,
  INDEX `Index_6` (`placa` ASC) VISIBLE,
  INDEX `Index_7` (`marca` ASC) VISIBLE,
  INDEX `Index_8` (`tipo` ASC) VISIBLE,
  INDEX `Index_9` (`licencia` ASC) VISIBLE,
  INDEX `Index_10` (`impuso` ASC) VISIBLE,
  CONSTRAINT `FK_sanciones_1`
    FOREIGN KEY (`reporte_num`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`),
  CONSTRAINT `FK_sanciones_2`
    FOREIGN KEY (`falta`)
    REFERENCES `cop2009`.`faltas` (`ARTICULO`))
ENGINE = InnoDB
AUTO_INCREMENT = 44480
DEFAULT CHARACTER SET = latin1



-- UTILIZACION_RAMPA_FRENADO
CREATE TABLE IF NOT EXISTS `cop2009`.`utilizacion_rampa_frenado` (
  `Id` DOUBLE UNSIGNED NOT NULL AUTO_INCREMENT,
  `Id_reporte` DOUBLE UNSIGNED NOT NULL,
  `tipo_vehiculo` VARCHAR(255) NULL DEFAULT NULL,
  `Marca` VARCHAR(20) NULL DEFAULT NULL,
  `Placa` VARCHAR(255) NULL DEFAULT NULL,
  `TIPO_TRANSPORTE` VARCHAR(20) NULL DEFAULT NULL,
  `PILOTO_NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `NUMERO_LICENCIA` VARCHAR(50) NULL DEFAULT NULL,
  `TIPO_LICENCIA` VARCHAR(1) NULL DEFAULT NULL,
  `EDAD` INT(3) UNSIGNED NULL DEFAULT NULL,
  `SEXO` VARCHAR(10) NULL DEFAULT NULL,
  `SUPUESTA_CAUSA` VARCHAR(50) NULL DEFAULT NULL,
  `SEGURO` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_reporte` (`Id_reporte` ASC) VISIBLE,
  INDEX `TIPO_TRANSPORTEUTILIZACION_RAMP` (`TIPO_TRANSPORTE` ASC) VISIBLE,
  INDEX `TIPO_VEHICULOUTILIZACION_RAMPA_` (`tipo_vehiculo` ASC) VISIBLE,
  CONSTRAINT `FK_utilizacion_rampa_frenado_1`
    FOREIGN KEY (`Id_reporte`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1



-- TIPO_OPERATIVOS_ESPECIALES
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_operativos_especiales` (
  `TIPO_OPERATIVO_ESPECIAL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_OPERATIVO_ESPECIAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


-- LLAMADAS_RECIBIDAS
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_operativos_especiales` (
  `TIPO_OPERATIVO_ESPECIAL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_OPERATIVO_ESPECIAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--BRIGADAS
CREATE TABLE IF NOT EXISTS `cop2009`.`brigadas` (
  `NUM_PLACA` VARCHAR(10) NOT NULL,
  `BRIGADA_NOM` VARCHAR(50) NULL DEFAULT NULL,
  `BRIGADA_NIT` VARCHAR(15) NULL DEFAULT NULL,
  `TELEFONO1` VARCHAR(10) NULL DEFAULT NULL,
  `TELEFONO2` VARCHAR(10) NULL DEFAULT NULL,
  `TELEFONO3` VARCHAR(10) NULL DEFAULT NULL,
  `TELEFONO4` VARCHAR(10) NULL DEFAULT NULL,
  `ACTIVO` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`NUM_PLACA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



-- INFO_DE_RUTA
CREATE TABLE IF NOT EXISTS `cop2009`.`infoderuta` (
  `REPORTE_NUM` DOUBLE NOT NULL DEFAULT '0',
  `AFLU_VEH_PARTICULAR` INT(10) UNSIGNED NULL DEFAULT NULL,
  `AFLU_VEH_TRANSCARGA` INT(10) UNSIGNED NULL DEFAULT NULL,
  `AFLU_VEH_TRANSPASAJEROS` INT(10) UNSIGNED NULL DEFAULT NULL,
  `OBSERS` VARCHAR(250) NULL DEFAULT NULL,
  `CLIMA` VARCHAR(50) NULL DEFAULT NULL,
  `TRAFICO` VARCHAR(50) NULL DEFAULT NULL,
  `NUM` DOUBLE UNSIGNED NOT NULL AUTO_INCREMENT,
  `KL` DECIMAL(8,3) UNSIGNED NULL DEFAULT '0.000',
  `RUTA` VARCHAR(20) NOT NULL DEFAULT '-',
  `DIRECCION` VARCHAR(15) NOT NULL DEFAULT '-',
  `FECHA_HORA` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`NUM`),
  INDEX `REPORTE_NUM` USING BTREE (`REPORTE_NUM`) VISIBLE,
  CONSTRAINT `FK_infoderuta_1`
    FOREIGN KEY (`REPORTE_NUM`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`)
    ON UPDATE CASCADE,
  CONSTRAINT `FK_infoderuta_2`
    FOREIGN KEY (`REPORTE_NUM`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`))
ENGINE = InnoDB
AUTO_INCREMENT = 231
DEFAULT CHARACTER SET = latin1



--TIPO_OPERATIVOS_ESPECIALES
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_operativos_especiales` (
  `TIPO_OPERATIVO_ESPECIAL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_OPERATIVO_ESPECIAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--BUSES_EXTRAURBANOS
CREATE TABLE IF NOT EXISTS `cop2009`.`busesextraurbanos` (
  `BUS_PLACA` VARCHAR(10) NOT NULL,
  `EMPRESA_NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `BUS_RUTA_DE` INT(10) NULL DEFAULT NULL,
  `BUS_RUTA_HACIA` INT(10) NULL DEFAULT NULL,
  `EMPRESA_LICENCIA_NO` VARCHAR(255) NULL DEFAULT NULL,
  `BUS_TARJETA_OPERACION` VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVACIONES` LONGTEXT NULL DEFAULT NULL,
  `FECHA_HORA` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`BUS_PLACA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--ESTDTEMP
CREATE TABLE IF NOT EXISTS `cop2009`.`estdtemp` (
  `GRUPO` VARCHAR(45) NOT NULL,
  `ORIENTE` INT(11) NOT NULL,
  `NORTE` INT(11) NOT NULL,
  `SUR` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--UNIDADES
CREATE TABLE IF NOT EXISTS `cop2009`.`unidades` (
  `UNIDAD_NUM` VARCHAR(10) NOT NULL DEFAULT '0',
  `UNIDAD_TIPO` SMALLINT(5) NULL DEFAULT NULL,
  `GPS` TINYINT(1) NOT NULL,
  `WINCH` TINYINT(1) NOT NULL,
  `RADAR` TINYINT(1) NOT NULL,
  `BALISA` TINYINT(1) NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL,
  `BLOCK` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `OBS` VARCHAR(50) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(15) NOT NULL DEFAULT '-',
  PRIMARY KEY (`UNIDAD_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--BLOQUEOS
CREATE TABLE IF NOT EXISTS `cop2009`.`bloqueos` (
  `reporte_num` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `OBJETO_BLOQUEA` VARCHAR(50) NULL DEFAULT NULL,
  `GRUPO_SOCIAL` VARCHAR(50) NULL DEFAULT NULL,
  `DEMANDAS` VARCHAR(100) NULL DEFAULT NULL,
  `heridos_mujeres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_mujeres_adultas` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_hombres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_hombres_adultos` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_mujeres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_mujeres_adultas` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_hombres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `TRASLADADOS_A` VARCHAR(100) NULL DEFAULT NULL,
  `AUTORIDADES_PRESENTES` VARCHAR(150) NULL DEFAULT NULL,
  `muertos_hombres_adultos` INT(3) UNSIGNED NULL DEFAULT NULL,
  `otrosasisten` VARCHAR(45) NULL DEFAULT '-',
  PRIMARY KEY (`reporte_num`),
  INDEX `Id_reporte` (`reporte_num` ASC) VISIBLE,
  INDEX `REPORTES_OPERATIVOSBLOQUEOS` (`reporte_num` ASC) VISIBLE,
  CONSTRAINT `FK_bloqueos_1`
    FOREIGN KEY (`reporte_num`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--LICENCIA_VIAL
CREATE TABLE IF NOT EXISTS `cop2009`.`accidente_vial` (
  `REPORTE_NUM` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `numero_acc` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaing` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `usuario` VARCHAR(50) NULL DEFAULT '0',
  `Tipoacc` VARCHAR(50) NOT NULL DEFAULT '-',
  `fechacc` DATE NULL DEFAULT '0000-00-00',
  `horaacc` TIME NULL DEFAULT '00:00:00',
  `contob` VARCHAR(50) NULL DEFAULT '-',
  `atrop` VARCHAR(50) NULL DEFAULT '-',
  `perid` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `nomper` VARCHAR(50) NULL DEFAULT '-',
  `perfallf` INT(10) UNSIGNED NULL DEFAULT '0',
  `perfafmen` INT(10) UNSIGNED NULL DEFAULT '0',
  `perfafmay` INT(10) UNSIGNED NULL DEFAULT '0',
  `perfallm` INT(10) UNSIGNED NULL DEFAULT '0',
  `perfammen` INT(10) UNSIGNED NULL DEFAULT '0',
  `perfammay` INT(10) UNSIGNED NULL DEFAULT '0',
  `perherf` INT(10) UNSIGNED NULL DEFAULT '0',
  `perhfmen` INT(10) UNSIGNED NULL DEFAULT '0',
  `perhfmay` INT(10) UNSIGNED NULL DEFAULT '0',
  `perherm` INT(10) UNSIGNED NULL DEFAULT '0',
  `perhmmen` INT(10) UNSIGNED NULL DEFAULT '0',
  `perhmmay` INT(10) UNSIGNED NULL DEFAULT '0',
  `lugtigss` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `datigss` VARCHAR(50) NULL DEFAULT '-',
  `lugthos` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `dathos` VARCHAR(50) NULL DEFAULT '-',
  `lugtsan` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `datsan` VARCHAR(50) NULL DEFAULT '-',
  `autppnc` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `autpmp` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `autpbm` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `autpbv` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `autpot` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `autpote` VARCHAR(50) NULL DEFAULT '-',
  `carret` VARCHAR(50) NULL DEFAULT '-',
  `carreto` VARCHAR(50) NULL DEFAULT '-',
  `kilometro` DOUBLE(7,2) UNSIGNED NULL DEFAULT '0.00',
  `kilodir` VARCHAR(50) NULL DEFAULT '-',
  `longd` VARCHAR(50) NULL DEFAULT '-',
  `pend` VARCHAR(50) NULL DEFAULT '-',
  `direcc` VARCHAR(50) NULL DEFAULT '-',
  `super` VARCHAR(50) NULL DEFAULT '-',
  `cond` VARCHAR(50) NULL DEFAULT '-',
  `dert` VARCHAR(50) NULL DEFAULT '-',
  `tshor` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `tshbor` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `tsver` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `tssin` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `cdclim` VARCHAR(50) NULL DEFAULT '-',
  `tipclim` VARCHAR(50) NULL DEFAULT '-',
  `tipacc` VARCHAR(50) NULL DEFAULT '-',
  `dañveh` VARCHAR(50) NULL DEFAULT '-',
  `dañinf` VARCHAR(50) NULL DEFAULT '-',
  `dañinfe` VARCHAR(150) NULL DEFAULT '-',
  `hipev` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipff` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipfss` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipell` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipbd` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipht` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hiprlp` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipcbel` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipec` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipep` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipcme` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipcp` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hibp` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hiplc` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipmlsc` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipmssc` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hiprvnh` TINYINT(1) UNSIGNED NULL DEFAULT '0',
  `hipot` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`numero_acc`),
  UNIQUE INDEX `REPORTE_NUM` (`REPORTE_NUM` ASC) VISIBLE,
  INDEX `numero_acc` (`numero_acc` ASC) VISIBLE,
  INDEX `Index_4` (`fechacc` ASC) VISIBLE,
  INDEX `Index_5` (`fechaing` ASC) VISIBLE,
  INDEX `Index_6` (`Tipoacc` ASC) VISIBLE,
  CONSTRAINT `FK_accidente_vial_1`
    FOREIGN KEY (`REPORTE_NUM`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`))
ENGINE = InnoDB
AUTO_INCREMENT = 13919
DEFAULT CHARACTER SET = latin1


--USUARIO
CREATE TABLE IF NOT EXISTS `cop2009`.`usuarios` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `USUARIOC4` VARCHAR(15) NOT NULL,
  `PASSWORD` VARCHAR(20) NULL DEFAULT NULL,
  `ACCESO` TINYINT(1) NOT NULL,
  `C4` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`, `USUARIOC4`),
  UNIQUE INDEX `ID` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `USUARIOC4` (`USUARIOC4` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 218
DEFAULT CHARACTER SET = latin1


--DERRUMBES
CREATE TABLE IF NOT EXISTS `cop2009`.`derrumbes` (
  `reporte_num` DOUBLE UNSIGNED NOT NULL DEFAULT '0',
  `magnitud_obstruccion` VARCHAR(50) NULL DEFAULT NULL,
  `clima` VARCHAR(255) NULL DEFAULT NULL,
  `longitud` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_mujeres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_mujeres_adultas` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_hombres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `heridos_hombres_adultos` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_mujeres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_mujeres_adultas` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_hombres_menores` INT(3) UNSIGNED NULL DEFAULT NULL,
  `muertos_hombres_adultos` INT(3) UNSIGNED NULL DEFAULT NULL,
  `personas_asistidas` INT(3) UNSIGNED NULL DEFAULT NULL,
  `se_coordino_con` VARCHAR(150) NULL DEFAULT NULL,
  `RECTACURVA` VARCHAR(5) NULL DEFAULT NULL,
  `otrosasisten` VARCHAR(45) NULL DEFAULT '-',
  PRIMARY KEY (`reporte_num`),
  INDEX `Id_reporte` (`reporte_num` ASC) VISIBLE,
  CONSTRAINT `FK_derrumbes_1`
    FOREIGN KEY (`reporte_num`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--SECTORES
CREATE TABLE IF NOT EXISTS `cop2009`.`sectores` (
  `SECTOR_NOMBRE` VARCHAR(20) NOT NULL,
  `SECTOR_INICIO` SMALLINT(5) NULL DEFAULT NULL,
  `SECTOR_FIN` SMALLINT(5) NULL DEFAULT NULL,
  `SENTIDO_INCREMENTA` VARCHAR(20) NULL DEFAULT NULL,
  `SENTIDO_DECREMENTA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SECTOR_NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--TIPO_OPERATIVOS_VIALES
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_operativos_viales` (
  `TIPO_OPERATIVO_VIAL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_OPERATIVO_VIAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



-- MARCA
CREATE TABLE IF NOT EXISTS `cop2009`.`marcas` (
  `MARCA_DES` VARCHAR(20) NOT NULL DEFAULT '-',
  PRIMARY KEY (`MARCA_DES`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



-- PATRULLAJES
CREATE TABLE IF NOT EXISTS `cop2009`.`patrullajes` (
  `UNIDAD_NUM` VARCHAR(10) NOT NULL DEFAULT '0',
  `DIA_TURNO` DATE NOT NULL DEFAULT '0000-00-00',
  `ULTIMO_REPORTE` DOUBLE UNSIGNED NULL DEFAULT NULL,
  `HORA_SALIO` TIME NULL DEFAULT '00:00:00',
  `ODO_SALIO` INT(10) NULL DEFAULT NULL,
  `FULL_SALIO` VARCHAR(5) NULL DEFAULT NULL,
  `HORA_ENTRO` TIME NULL DEFAULT '00:00:00',
  `ODO_ENTRO` INT(10) NULL DEFAULT NULL,
  `FULL_ENTRO` VARCHAR(5) NULL DEFAULT NULL,
  `COMISION` LONGTEXT NULL DEFAULT NULL,
  `ULTIMO_ESTADO` VARCHAR(20) NULL DEFAULT NULL,
  `INFO` LONGTEXT NULL DEFAULT NULL,
  `LLA_ATENCION` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNIDAD_NUM`, `DIA_TURNO`),
  INDEX `PATRULLAJESDIA_TURNO` (`DIA_TURNO` ASC) VISIBLE,
  INDEX `REPORTES_OPERATIVOSPATRULLAJES` (`ULTIMO_REPORTE` ASC) VISIBLE,
  INDEX `UNIDADESPATRULLAJES` (`UNIDAD_NUM` ASC) VISIBLE,
  INDEX `UNIDADESPATRULLAJES1` (`UNIDAD_NUM` ASC) VISIBLE,
  CONSTRAINT `FK_patrullajes_1`
    FOREIGN KEY (`UNIDAD_NUM` , `DIA_TURNO`)
    REFERENCES `cop2009`.`unidades_sectores` (`UNIDAD_NUM` , `DIA_TURNO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


-- TIPOS_TRABAJOS_ENCARRETERA
CREATE TABLE IF NOT EXISTS `cop2009`.`tipos_de_trabajos_encarretera` (
  `TIPO_TRABAJO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_TRABAJO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



-- FALTAS
CREATE TABLE IF NOT EXISTS `cop2009`.`faltas` (
  `ARTICULO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ARTICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--REINCIDENCIAS_FLAT
CREATE TABLE IF NOT EXISTS `cop2009`.`reincidencias_flat` (
  `IDENTIFICADOR` VARCHAR(50) NULL DEFAULT NULL,
  `REINCIDENCIAS` VARCHAR(50) NULL DEFAULT NULL,
  `EVENTO` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `ID` (`IDENTIFICADOR` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--TIPO_LLAMADAS_RECIBIDAS
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_llamadas_recibidas` (
  `LLAMADA_TIPO` VARCHAR(50) NOT NULL DEFAULT '-',
  PRIMARY KEY (`LLAMADA_TIPO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



-- VEHICULOS_INVOLUCRADOS
CREATE TABLE IF NOT EXISTS `cop2009`.`vehiculos_involucrados` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `REPORTE_NUM` DOUBLE NULL DEFAULT NULL,
  `numero_acc` INT(10) NULL DEFAULT NULL,
  `fechaing` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `tipoveh` VARCHAR(50) NULL DEFAULT NULL,
  `marcav` VARCHAR(50) NULL DEFAULT NULL,
  `tracam` VARCHAR(50) NULL DEFAULT NULL,
  `estdveh` VARCHAR(50) NULL DEFAULT NULL,
  `placav` VARCHAR(10) NOT NULL DEFAULT '0',
  `tiptrans` VARCHAR(50) NULL DEFAULT NULL,
  `nomempr` VARCHAR(50) NULL DEFAULT NULL,
  `tarjcirc` VARCHAR(50) NULL DEFAULT NULL,
  `tarjoper` VARCHAR(50) NULL DEFAULT NULL,
  `tiptcp` VARCHAR(50) NULL DEFAULT NULL,
  `cantveh` INT(10) NULL DEFAULT NULL,
  `nompil` VARCHAR(50) NULL DEFAULT NULL,
  `licenno` VARCHAR(50) NULL DEFAULT NULL,
  `tiplicen` VARCHAR(50) NULL DEFAULT NULL,
  `estpil` VARCHAR(50) NULL DEFAULT NULL,
  `sexo` VARCHAR(50) NULL DEFAULT NULL,
  `edad` INT(10) NULL DEFAULT NULL,
  `segsn` VARCHAR(50) NULL DEFAULT NULL,
  `segnom` VARCHAR(50) NULL DEFAULT NULL,
  `segvig` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`ID`, `placav`),
  INDEX `ID` (`ID` ASC) VISIBLE,
  INDEX `numero_acc` (`numero_acc` ASC) VISIBLE,
  INDEX `REPORTE_NUM` (`REPORTE_NUM` ASC) VISIBLE,
  INDEX `Index_5` (`placav` ASC) VISIBLE,
  INDEX `Index_6` (`licenno` ASC) VISIBLE,
  INDEX `FK_vehiculos_involucrados_3` (`tipoveh` ASC) VISIBLE,
  INDEX `Index_9` (`marcav` ASC) VISIBLE,
  CONSTRAINT `FK_vehiculos_involucrados_1`
    FOREIGN KEY (`REPORTE_NUM`)
    REFERENCES `cop2009`.`reportes_operativos` (`REPORTE_NUM`),
  CONSTRAINT `FK_vehiculos_involucrados_2`
    FOREIGN KEY (`marcav`)
    REFERENCES `cop2009`.`marcas` (`MARCA_DES`),
  CONSTRAINT `FK_vehiculos_involucrados_3`
    FOREIGN KEY (`tipoveh`)
    REFERENCES `cop2009`.`tipo_vehiculo` (`DES_VEHICULO`))
ENGINE = InnoDB
AUTO_INCREMENT = 20976
DEFAULT CHARACTER SET = latin1



--REPORTES_OPERATIVOS
CREATE TABLE IF NOT EXISTS `cop2009`.`reportes_operativos` (
  `REPORTE_NUM` DOUBLE NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL DEFAULT '0000-00-00',
  `HORA` TIME NOT NULL DEFAULT '00:00:00',
  `UNIDAD_NUM` VARCHAR(10) NOT NULL DEFAULT '0',
  `SECTOR` VARCHAR(20) NOT NULL,
  `UBICACION` DECIMAL(8,3) NOT NULL DEFAULT '0.000',
  `DIRECC_SENTIDO` VARCHAR(25) NOT NULL,
  `REPORTE_TIPO` VARCHAR(50) NOT NULL,
  `USUARIO` VARCHAR(15) NOT NULL,
  `VALIDADO` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`REPORTE_NUM`),
  UNIQUE INDEX `SANCIONESREPORTES_OPERATIVOS` (`REPORTE_NUM` ASC) VISIBLE,
  INDEX `FECHA_HORA` (`FECHA` ASC) VISIBLE,
  INDEX `fechareporte` (`FECHA` ASC) VISIBLE,
  INDEX `REPORTE_TIPO` (`REPORTE_TIPO` ASC) VISIBLE,
  INDEX `SECTOR_COD` (`SECTOR` ASC) VISIBLE,
  INDEX `SECTORESREPORTES_OPERATIVOS` (`SECTOR` ASC) VISIBLE,
  INDEX `TIPOS_REPORTEREPORTES_OPERATIVOS` (`REPORTE_TIPO` ASC) VISIBLE,
  INDEX `UNIDAD_NUM` (`UNIDAD_NUM` ASC) VISIBLE,
  INDEX `UNIDADESREPORTES_OPERATIVOS1` (`UNIDAD_NUM` ASC) VISIBLE,
  INDEX `unidadreporte` (`UNIDAD_NUM` ASC) VISIBLE,
  CONSTRAINT `FK_reportes_operativos_1`
    FOREIGN KEY (`SECTOR`)
    REFERENCES `cop2009`.`sectores` (`SECTOR_NOMBRE`),
  CONSTRAINT `FK_reportes_operativos_2`
    FOREIGN KEY (`UNIDAD_NUM`)
    REFERENCES `cop2009`.`unidades` (`UNIDAD_NUM`))
ENGINE = InnoDB
AUTO_INCREMENT = 2188733
DEFAULT CHARACTER SET = latin1


--INSTITUCIONES
CREATE TABLE IF NOT EXISTS `cop2009`.`instituciones` (
  `INSTITUCION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`INSTITUCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--OPERATIVOS_VIALES
CREATE TABLE IF NOT EXISTS `cop2009`.`operativos_viales` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `TIPO_OPERATIVO_VIAL` VARCHAR(100) NULL DEFAULT NULL,
  `SECTOR` VARCHAR(50) NULL DEFAULT NULL,
  `KILOMETRO` DECIMAL(8,0) NULL DEFAULT NULL,
  `UNIDAD` VARCHAR(10) NULL DEFAULT NULL,
  `PILOTO` INT(10) NULL DEFAULT NULL,
  `COPILOTO` INT(10) NULL DEFAULT NULL,
  `FECHA_INICIO` DATETIME NULL DEFAULT NULL,
  `FECHA_FINALIZA` DATETIME NULL DEFAULT NULL,
  `INSTITUCION_APOYO` VARCHAR(50) NULL DEFAULT NULL,
  `V_EN_APOYO` INT(10) NULL DEFAULT NULL,
  `V_REVISADOS` INT(10) NULL DEFAULT NULL,
  `V_SANCIONADOS` INT(10) NULL DEFAULT NULL,
  `LLAMADAS_ATENCION` INT(10) NULL DEFAULT NULL,
  `NOVEDADES` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `BRIGADASOPERATIVOS_VIALES` (`PILOTO` ASC) VISIBLE,
  INDEX `BRIGADASOPERATIVOS_VIALES1` (`COPILOTO` ASC) VISIBLE,
  INDEX `INSTITUCIONESOPERATIVOS_VIALES` (`INSTITUCION_APOYO` ASC) VISIBLE,
  INDEX `SECTORESOPERATIVOS_VIALES` (`SECTOR` ASC) VISIBLE,
  INDEX `TIPO_OPERATIVOS_VIALESOPERATIVO` (`TIPO_OPERATIVO_VIAL` ASC) VISIBLE,
  INDEX `UNIDADESOPERATIVOS_VIALES1` (`UNIDAD` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--LLAMADAS_REALIZADAS
CREATE TABLE IF NOT EXISTS `cop2009`.`llamadas_realizadas` (
  `ID` DOUBLE UNSIGNED NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL DEFAULT '0000-00-00',
  `HORA` TIME NOT NULL DEFAULT '00:00:00',
  `DESTINO` VARCHAR(15) NOT NULL DEFAULT '0',
  `MOTIVO` VARCHAR(50) NOT NULL,
  `EN_APOYO_A` VARCHAR(50) NOT NULL,
  `DESCRIPCION_APOYADO` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Index_3` (`FECHA` ASC) VISIBLE,
  INDEX `Index_4` (`EN_APOYO_A` ASC) VISIBLE,
  INDEX `Index_5` (`FECHA` ASC, `EN_APOYO_A` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 113
DEFAULT CHARACTER SET = latin1


--TIPO_REPORTE
CREATE TABLE IF NOT EXISTS `cop2009`.`tipos_reporte` (
  `TREPORTE_DES` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TREPORTE_DES`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1


--TIPO_VEHICULO
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_vehiculo` (
  `DES_VEHICULO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DES_VEHICULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--UNIDADES_SECTORES
CREATE TABLE IF NOT EXISTS `cop2009`.`unidades_sectores` (
  `SECTOR_CODIGO` VARCHAR(20) NOT NULL DEFAULT '-',
  `UNIDAD_NUM` VARCHAR(10) NOT NULL,
  `DIA_TURNO` DATE NOT NULL DEFAULT '0000-00-00',
  `UNIDA_BRIGADA1` INT(10) NOT NULL,
  `UNIDA_BRIGADA2` INT(10) NOT NULL,
  `HORA_INICIO` TIME NOT NULL DEFAULT '00:00:00',
  `HORA_FINAL` TIME NOT NULL DEFAULT '00:00:00',
  PRIMARY KEY (`UNIDAD_NUM`, `DIA_TURNO`),
  INDEX `BRIGADASUNIDADES_SECTORES` (`UNIDA_BRIGADA1` ASC) VISIBLE,
  INDEX `BRIGADASUNIDADES_SECTORES1` (`UNIDA_BRIGADA2` ASC) VISIBLE,
  INDEX `SECTORESUNIDADES_SECTORES` (`SECTOR_CODIGO` ASC) VISIBLE,
  INDEX `UNIDAD_NUM1` (`UNIDAD_NUM` ASC) VISIBLE,
  INDEX `UNIDADES_SECTORESDIA_TURNO` (`DIA_TURNO` ASC) VISIBLE,
  INDEX `UNIDAD_NUM` (`UNIDAD_NUM` ASC) VISIBLE,
  INDEX `UNIDADESUNIDADES_SECTORES` (`SECTOR_CODIGO` ASC, `UNIDAD_NUM` ASC) VISIBLE,
  CONSTRAINT `FK_unidades_sectores_1`
    FOREIGN KEY (`SECTOR_CODIGO`)
    REFERENCES `cop2009`.`sectores` (`SECTOR_NOMBRE`),
  CONSTRAINT `FK_unidades_sectores_2`
    FOREIGN KEY (`UNIDAD_NUM`)
    REFERENCES `cop2009`.`unidades` (`UNIDAD_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--TIPO_TRANSPORTE
CREATE TABLE IF NOT EXISTS `cop2009`.`tipo_transporte` (
  `TIPO_TRANSPORTE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIPO_TRANSPORTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--V_EN_APOYO_OV
CREATE TABLE IF NOT EXISTS `cop2009`.`v_en_apoyo_ov` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `Id_OPERATIVO` INT(10) NULL DEFAULT NULL,
  `INSTITUCION` VARCHAR(50) NULL DEFAULT NULL,
  `PLACA` VARCHAR(255) NULL DEFAULT NULL,
  `TRIPULACION1` VARCHAR(50) NULL DEFAULT NULL,
  `TRIPULACION2` VARCHAR(50) NULL DEFAULT NULL,
  `TRIPULACION3` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_OPERATIVO` (`Id_OPERATIVO` ASC) VISIBLE,
  INDEX `INSTITUCIONESV_EN_APOYO_OV` (`INSTITUCION` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--OPERATIVOS_ESPECIALES
CREATE TABLE IF NOT EXISTS `cop2009`.`operativos_especiales` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `UNIDAD` VARCHAR(10) NULL DEFAULT NULL,
  `PILOTO` INT(10) NULL DEFAULT NULL,
  `COPILOTO` INT(10) NULL DEFAULT NULL,
  `OTROS_TRIPULANTES` INT(10) NULL DEFAULT NULL,
  `TIPO_DE_APOYO` VARCHAR(255) NULL DEFAULT NULL,
  `TIPO_TRABAJO` VARCHAR(50) NULL DEFAULT NULL,
  `SECTOR` VARCHAR(20) NULL DEFAULT NULL,
  `SENTIDO` VARCHAR(20) NULL DEFAULT NULL,
  `KL_DEL` INT(10) NULL DEFAULT NULL,
  `KL_AL` VARCHAR(255) NULL DEFAULT NULL,
  `SOLICITO` VARCHAR(50) NULL DEFAULT NULL,
  `EMPRESA` VARCHAR(50) NULL DEFAULT NULL,
  `HORA_INICIA` DATETIME NULL DEFAULT NULL,
  `HORA_FINALIZA` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `BRIGADASOPERATIVOS_ESPECIALES` (`PILOTO` ASC) VISIBLE,
  INDEX `BRIGADASOPERATIVOS_ESPECIALES1` (`COPILOTO` ASC) VISIBLE,
  INDEX `SECTORESOPERATIVOS_ESPECIALES` (`SECTOR` ASC) VISIBLE,
  INDEX `SECTORESOPERATIVOS_ESPECIALES1` (`SECTOR` ASC) VISIBLE,
  INDEX `TIPO_OPERATIVOS_ESPECIALESOPERA` (`TIPO_DE_APOYO` ASC) VISIBLE,
  INDEX `TIPOS_DE_TRABAJOS_ENCARRETERAOP` (`TIPO_TRABAJO` ASC) VISIBLE,
  INDEX `UNIDADESOPERATIVOS_ESPECIALES` (`UNIDAD` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1



--C_ODOMETRO
CREATE TABLE IF NOT EXISTS `cop2009`.`c_odometro` (
  `UNIDAD_NUM` INT(11) NOT NULL,
  `USUARIO` VARCHAR(45) NOT NULL,
  `FECHA` VARCHAR(45) NOT NULL,
  `ODO_ANT` INT(11) NOT NULL,
  `ODO_NUE` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1

-------------------------------------------------------------------------------------------------------



